<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tag;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getWithTags()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select('p', 't')
            ->from('AppBundle:Post', 'p')
            ->leftJoin('p.tags', 't')
            ->getQuery()
            ->getResult();
    }

    public function getByTag(Tag $tag)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select('p', 't')
            ->from('AppBundle:Post', 'p')
            ->leftJoin('p.tags', 't')
            ->where(':tag MEMBER OF p.tags')
            ->setParameter('tag', $tag)
            ->getQuery()
            ->getResult();
    }
}
