<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllWithPostsCount()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select('t.title', 'COUNT(p.id) as countOfPosts')
            ->from('AppBundle:Tag', 't')
            ->innerJoin('t.posts', 'p')
            ->groupBy('t.id')
            ->orderBy('t.title')
            ->getQuery()
            ->getResult();
    }
}
