# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.query_posts_with_tags:
        class:    AppBundle\QueryFunction\Post\PostsWithTags
        autowire: true

    app.query_posts_by_tag:
        class:    AppBundle\QueryFunction\Post\PostsByTag
        autowire: true

    app.query_tags_with_posts_count:
        class:    AppBundle\QueryFunction\Tag\TagsWithPostsCount
        autowire: true

    app.query_user_groups_with_users_count:
        class:    AppBundle\QueryFunction\UserGroup\GroupsWithUsersCount
        autowire: true

    app.query_groups_by_user:
        class:    AppBundle\QueryFunction\UserGroup\GroupsByUser
        autowire: true

    app.query_books_with_authors_count:
        class:    AppBundle\QueryFunction\Book\BooksWithAuthorsCount
        autowire: true
